### ISSUE TITLE
wfdb repository 

### ISSUE THREAD

**Issue by shemla** [physiozoo/physiozoo#6]
There has been an update for the wfdb tools lately, and the link to download the repo in mhrv_init.m doesn't work.
we can either change the link to its new location in physionet's archives, somewhere in https://physionet.org/physiotools/archives/wfdb-10.5/
or change the link to the newest version (and run a quick check to make sure it doesn't hurt any of our functions), from 
https://physionet.org/physiotools/binaries/windows/

**Comment by shemla** [comment]
correction - the links are in download_wfdb.m

**Comment by avivrosenberg** [comment]
I've pushed a version with fixed links to the windows binaries - e2d45fe.

@goldina please add an updated installer to [v1.1.3](https://github.com/physiozoo/physiozoo/releases/edit/v1.1.3) and let me know when it's up so i can update the download links on the PhysioZoo website.

**Comment by goldina** [comment]
Done

**Comment by jbehar** [comment]
Alexandra, do you mind checking everything works when installing the new
version?
Thanks,
Jo

**Comment by goldina** [comment]
במחשב שלי - עובד....
ביקשתי מאורי גם לעשות בדיקות

On 4 Dec 2018, at 16:24, jbehar <notifications@github.com<mailto:notifications@github.com>> wrote:

Alexandra, do you mind checking everything works when installing the new
version?
Thanks,
Jo

**Comment by jbehar** [comment]
perfect. Thanks Sacha,
Joachim

**Comment by goldina** [comment]
Sasha סשה
ולא סצ׳ה Sacha 😜😜😜😜

On 4 Dec 2018, at 18:54, jbehar <notifications@github.com<mailto:notifications@github.com>> wrote:

perfect. Thanks Sacha,
Joachim

**Comment by shemla** [comment]
good job guys, I just checked the main functions work in the new version and everything looks good. I close this issue
