### ISSUE TITLE
my_WindowScrollWheelFcn

### ISSUE THREAD

**Issue by shemla** [physiozoo/physiozoo#9]
On laptop mouse-pad, it is possible that the variable VerticalScrollCount will get a value of 0. this case should be understood and dealt with. To date, in the scroll bar (the lower figure of the RR in module 2 or the RR figure in module 1) when scrolling the mouse pad, Matlab returns an error. The GUI isn't interrupted, and the functionality is preserved.

**Comment by goldina** [comment]
Done
